openapi: '3.0.2'
info:
  title: userinfo API
  description: |-
    This is a description of the API for quering information about a specific user.
    It's normally called through Camunda.
  termsOfService: http://swagger.io/terms/
  contact:
    email: digit@haninge.se
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8000
  - url: https://camunda-wrapper.k8s.violaberg.nu/worker
  - url: https://camunda-wrapper.dev.digit.haninge.se/worker
paths:
  /userinfo:
    get:
      parameters:
        - name: userid
          in: query
          description: userid for user to query
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userinfo'
        '400':
          description: Bad request
components:
  schemas:
    userinfo:
      type: object
      properties:
        person_id:
          type: string
          example: 195512313551
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: James
        full_name:
          type: string
          example: John Arthur James
        address:
          type: string
          example: Violabergsvägen 4
        zipcode:
          type: string
          example: 13668
        city:
          type: string
          example: VENDELSÖ
        email:
          type: string
          example: hakan@violaberg.nu
        mobile:
          type: string
          example: 0702178177
